/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stoppuhr.gui;

import com.google.gson.Gson;
import com.sun.security.ntlm.Client;
import java.awt.Dimension;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.Socket;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import stoppuhr.server.Server;
import stoppuhr.server.Server.Request;
import stoppuhr.server.Server.Response;

/**
 *
 * @author Julian
 */
public class GuiStopwatch extends javax.swing.JFrame {

    /**
     * Creates new form Stopwatch
     */
    public GuiStopwatch() throws IOException {
        initComponents();
        setTitle("Client");
        setMinimumSize(new Dimension(300, 250));
        setSize(400, 300);
        jlClock.setText("0.000");

        jbutConnect.setEnabled(false);
        jbutClear.setEnabled(false);
        jbutDisconnect.setEnabled(false);
        jbutEnd.setEnabled(false);
        jbutStart.setEnabled(false);
        jbutStop.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jpanNorth = new javax.swing.JPanel();
        jl1s = new javax.swing.JLabel();
        jslidRefresh = new javax.swing.JSlider();
        jl1ms = new javax.swing.JLabel();
        jpanCenter = new javax.swing.JPanel();
        jlClock = new javax.swing.JLabel();
        jpanEast = new javax.swing.JPanel();
        jbutConnect = new javax.swing.JButton();
        jbutDisconnect = new javax.swing.JButton();
        jbutStart = new javax.swing.JButton();
        jbutStop = new javax.swing.JButton();
        jbutClear = new javax.swing.JButton();
        jbutEnd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpanNorth.setLayout(new java.awt.BorderLayout());

        jl1s.setText("Refreshrate 1s");
        jpanNorth.add(jl1s, java.awt.BorderLayout.WEST);

        jslidRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jpanNorth.add(jslidRefresh, java.awt.BorderLayout.CENTER);

        jl1ms.setText("1ms");
        jpanNorth.add(jl1ms, java.awt.BorderLayout.EAST);

        getContentPane().add(jpanNorth, java.awt.BorderLayout.NORTH);

        jpanCenter.setLayout(new java.awt.GridBagLayout());

        jlClock.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        jlClock.setText("0.000");
        jpanCenter.add(jlClock, new java.awt.GridBagConstraints());

        getContentPane().add(jpanCenter, java.awt.BorderLayout.CENTER);

        jpanEast.setLayout(new java.awt.GridBagLayout());

        jbutConnect.setText("Connect");
        jbutConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutConnectActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jpanEast.add(jbutConnect, gridBagConstraints);

        jbutDisconnect.setText("Disconnect");
        jbutDisconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutDisconnectActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jpanEast.add(jbutDisconnect, gridBagConstraints);

        jbutStart.setText("Start");
        jbutStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutStartActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jpanEast.add(jbutStart, gridBagConstraints);

        jbutStop.setText("Stop");
        jbutStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutStopActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jpanEast.add(jbutStop, gridBagConstraints);

        jbutClear.setText("Clear");
        jbutClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutClearActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jpanEast.add(jbutClear, gridBagConstraints);

        jbutEnd.setText("End");
        jbutEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutEndActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jpanEast.add(jbutEnd, gridBagConstraints);

        getContentPane().add(jpanEast, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbutConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutConnectActionPerformed
        System.out.println("Button pressed" + Thread.currentThread().getId());
        ConnectionWorker worker = new MyConnectionWorker(8080, "127.0.0.1");
        worker.execute();
    }//GEN-LAST:event_jbutConnectActionPerformed

    private void jbutDisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutDisconnectActionPerformed

    }//GEN-LAST:event_jbutDisconnectActionPerformed

    private void jbutStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutStartActionPerformed

    }//GEN-LAST:event_jbutStartActionPerformed

    private void jbutStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutStopActionPerformed


    }//GEN-LAST:event_jbutStopActionPerformed

    private void jbutClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutClearActionPerformed

    }//GEN-LAST:event_jbutClearActionPerformed

    private void jbutEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutEndActionPerformed


    }//GEN-LAST:event_jbutEndActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiStopwatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiStopwatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiStopwatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiStopwatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GuiStopwatch().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(GuiStopwatch.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    private class MyConnectionWorker extends ConnectionWorker {

        private Socket socket;
        private Response resp;

        public MyConnectionWorker(int port, String hostName) {
            super(port, hostName);
        }

        /*@Override
        protected void done() {

            try {
                String ergebnis = (String) get();
                System.out.println(ergebnis + " " + Thread.currentThread().getId());
                jlClock.setText(ergebnis);
            } catch (Exception ex) {
                ex.printStackTrace();
            }

        }*/
        @Override
        protected String doInBackground() throws Exception {
            final Gson gson = new Gson();
            final BufferedReader reader = new BufferedReader(new InputStreamReader(socket.getInputStream()));
            final OutputStreamWriter writer = new OutputStreamWriter(socket.getOutputStream());
            while (true) {
                try {
                    final Server.Request req = new Server.Request();
                    final String reqString = gson.toJson(req);
                    writer.write(reqString);
                    writer.flush();

                    final String respString = reader.readLine();
                    resp = gson.fromJson(respString, Response.class);
                    publish(resp);

                    Thread.sleep(1000);
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        }

        @Override
        protected void process(List<Response> list) {
            /*for (Response x : list) {
                System.out.println("Process " + x + " Thread " + Thread.currentThread().getId());
            }        }
             */
            Response resp = list.get(0);

            if (resp.isMaster()) {
                jbutClear.setEnabled(true);
                jbutConnect.setEnabled(false);
                jbutDisconnect.setEnabled(true);
                jbutEnd.setEnabled(true);
                jbutStart.setEnabled(true);
                jbutStop.setEnabled(true);
            }

            if (resp.isRunning()) {
                jlClock.setText(String.format("%.3f", resp.getTime()));
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbutClear;
    private javax.swing.JButton jbutConnect;
    private javax.swing.JButton jbutDisconnect;
    private javax.swing.JButton jbutEnd;
    private javax.swing.JButton jbutStart;
    private javax.swing.JButton jbutStop;
    private javax.swing.JLabel jl1ms;
    private javax.swing.JLabel jl1s;
    private javax.swing.JLabel jlClock;
    private javax.swing.JPanel jpanCenter;
    private javax.swing.JPanel jpanEast;
    private javax.swing.JPanel jpanNorth;
    private javax.swing.JSlider jslidRefresh;
    // End of variables declaration//GEN-END:variables

}
